name: Build toolchain

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions: write-all

jobs:
  trigger-build:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Hello World"
